plot \
'dpa.dat' index 0 notitle with lines linecolor 3,\
'dpa.dat' index 1 notitle with lines linecolor 3,\
'dpa.dat' index 2 notitle with lines linecolor 3,\
'dpa.dat' index 3 notitle with lines linecolor 3,\
'dpa.dat' index 4 notitle with lines linecolor 3,\
'dpa.dat' index 5 notitle with lines linecolor 3,\
'dpa.dat' index 6 notitle with lines linecolor 3,\
'dpa.dat' index 7 notitle with lines linecolor 3,\
'dpa.dat' index 8 notitle with lines linecolor 3,\
'dpa.dat' index 9 notitle with lines linecolor 3,\
'dpa.dat' index 10 notitle with lines linecolor 3,\
'dpa.dat' index 11 notitle with lines linecolor 3,\
'dpa.dat' index 12 notitle with lines linecolor 3,\
'dpa.dat' index 13 notitle with lines linecolor 3,\
'dpa.dat' index 14 notitle with lines linecolor 3,\
'dpa.dat' index 15 notitle with lines linecolor 3,\
'dpa.dat' index 16 notitle with lines linecolor 3,\
'dpa.dat' index 17 notitle with lines linecolor 3,\
'dpa.dat' index 18 notitle with lines linecolor 3,\
'dpa.dat' index 19 notitle with lines linecolor 3,\
'dpa.dat' index 20 notitle with lines linecolor 3,\
'dpa.dat' index 21 notitle with lines linecolor 3,\
'dpa.dat' index 22 notitle with lines linecolor 3,\
'dpa.dat' index 23 notitle with lines linecolor 3,\
'dpa.dat' index 24 notitle with lines linecolor 3,\
'dpa.dat' index 25 notitle with lines linecolor 3,\
'dpa.dat' index 26 notitle with lines linecolor 3,\
'dpa.dat' index 27 notitle with lines linecolor 3,\
'dpa.dat' index 28 notitle with lines linecolor 3,\
'dpa.dat' index 29 notitle with lines linecolor 3,\
'dpa.dat' index 30 notitle with lines linecolor 3,\
'dpa.dat' index 31 notitle with lines linecolor 3,\
'dpa.dat' index 32 notitle with lines linecolor 3,\
'dpa.dat' index 33 notitle with lines linecolor 3,\
'dpa.dat' index 34 notitle with lines linecolor 3,\
'dpa.dat' index 35 notitle with lines linecolor 3,\
'dpa.dat' index 36 notitle with lines linecolor 3,\
'dpa.dat' index 37 notitle with lines linecolor 3,\
'dpa.dat' index 38 notitle with lines linecolor 3,\
'dpa.dat' index 39 notitle with lines linecolor 3,\
'dpa.dat' index 40 notitle with lines linecolor 3,\
'dpa.dat' index 41 notitle with lines linecolor 3,\
'dpa.dat' index 42 notitle with lines linecolor 3,\
'dpa.dat' index 43 notitle with lines linecolor 3,\
'dpa.dat' index 44 notitle with lines linecolor 3,\
'dpa.dat' index 45 notitle with lines linecolor 3,\
'dpa.dat' index 46 notitle with lines linecolor 3,\
'dpa.dat' index 47 notitle with lines linecolor 3,\
'dpa.dat' index 48 notitle with lines linecolor 3,\
'dpa.dat' index 49 notitle with lines linecolor 3,\
'dpa.dat' index 50 notitle with lines linecolor 3,\
'dpa.dat' index 51 notitle with lines linecolor 3,\
'dpa.dat' index 52 notitle with lines linecolor 3,\
'dpa.dat' index 53 notitle with lines linecolor 3,\
'dpa.dat' index 55 notitle with lines linecolor 3,\
'dpa.dat' index 56 notitle with lines linecolor 3,\
'dpa.dat' index 57 notitle with lines linecolor 3,\
'dpa.dat' index 58 notitle with lines linecolor 3,\
'dpa.dat' index 59 notitle with lines linecolor 3,\
'dpa.dat' index 60 notitle with lines linecolor 3,\
'dpa.dat' index 61 notitle with lines linecolor 3,\
'dpa.dat' index 62 notitle with lines linecolor 3,\
'dpa.dat' index 63 notitle with lines linecolor 3,\
'dpa.dat' index 54 title 'Trace #54 (0x36)' with lines linecolor 1
